[module] Prevent std::string from nullptr
Traceback (most recent call last):
  File "./testgroup1.py", line 45, in <module>
    requires = aa.getDescription()
  File "/usr/lib64/python3.7/site-packages/libdnf/module.py", line 1304,
  in getDescription
    return _module.ModuleProfile_getDescription(self)
RuntimeError: basic_string::_M_construct null not valid

https://github.com/rpm-software-management/libdnf/issues/717

Closes: #726
Approved by: jrohel