Require specific version of libmodulemd
Otherwise it fails on combination of non updated F28 and nightly copr dnf,
searching non existent symbols:
ImportError: /lib64/libdnf.so.2: undefined symbol: modulemd_subdocument_get_gerror