HyPackageSet has been converted to a GObject
see fc9a4f0e0782eb014626beef39328cb37249fa23
fixing
/root/rpmbuild/BUILD/libhif-git-0.6f82114/libhif/hy-hth.c: In function ‘obsoletes’:
/root/rpmbuild/BUILD/libhif-git-0.6f82114/libhif/hy-hth.c:170:36: error: invalid initializer
     HifPackageSet installed_pkgs = hy_query_run_set(q);
                                    ^