libdnf/conf/OptionNumber.hpp: add missing <cstdint> include
Without the change libdnf build fails on this week's gcc-13 snapshot as:

    In file included from /build/libdnf/libdnf/conf/ConfigMain.hpp:29,
                     from /build/libdnf/libdnf/conf/ConfigMain.cpp:21:
    /build/libdnf/libdnf/conf/OptionNumber.hpp:94:41: error: 'int32_t' is not a member of 'std'; did you mean 'int32_t'?
       94 | extern template class OptionNumber<std::int32_t>;
          |                                         ^~~~~~~