[context] Fix bug if more repos directories do not exist
Existence of repos directories is not mandatory therefore the setting
of GError was removed.

Fixes the bug:
(microdnf:927715): GLib-WARNING **: 22:26:01.994: GError set over the
top of a previous GError or uninitialized memory. This indicates a bug
in someone's code. You must ensure an error is NULL before it's set.
The overwriting error message was: Error opening directory ?/etc/distro
.repos.d?: No such file or directory

(microdnf:927715): libdnf-CRITICAL **: 22:26:02.490: gboolean
dnf_state_set_steps_real(DnfState*, GError**, const gchar*, gint, ...):
assertion 'error == NULL || *error == NULL' failed
error: Error opening directory ?/etc/yum/repos.d?: No such file or
directory