Do not attempt to read from a closed file descriptor
This fixes a hard-to-trigger and even-harder-to-debug crash when installing
and then removing the same package. This will fix errors in the journal like:

    error: rpmdb: Packages: Bad file descriptor

Part of the yumdb core design is that the package 'key' is the SHA hash of the
rpmdb package header. By setting this during the transaction we do not have to
open the rpmdb when writing out the yumdb entry.

It appears that hy_sack_load_system_repo() -> repo_add_repodata() ->
repodata_empty() -> repodata_freedata() -> close() calls on the fd that we're
trying to share between different threads. The pread() and pwrite() system
calls were chosen in libsolv to make this possible, so we're not trying to
do anything unsupported and crazy.

We've got the rpm 'Header' already during the transaction, so it's easy to fix
by just extracting it there rather than looking it up once the transaction has
completed.

Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1183010