Context part of libdnf cannot assume zchunk is on (RhBug:1851841,1779104)
This was causing problems because if available only zchunk metadata was
donwloaded but later when individual repos are created and config is
loaded it couldn't be used if zchunk was off. This typically resulted in:
error: loading of MD_TYPE_PRIMARY has failed.

https://bugzilla.redhat.com/show_bug.cgi?id=1851841
https://bugzilla.redhat.com/show_bug.cgi?id=1779104

Closes: #998
Approved by: dmach